### ISSUE TITLE
Crash enabling midi devices in Studio mode - first time install - MacOS

### ISSUE THREAD

**Issue by jkoerts** [cpyarger/obs-midi#101]
## Platform

Operating system and version: macOS Big Sur 11.2.2
OBS Studio version: 26.1.2 (64 bit)

## Expected Behavior

Downloaded macOS install pakkage of obs-midi 0.9.3-ALPHA-3.3. Installed. Restarted Mac. Install of Jack not necessary.
Under Tools, first time opening OBS Midi Settings while OBS is in Studio mode.
Device is recognised (first try; Arturia Beatstep; 2nd try BCF-2000 Begringer controller (configured as Mackie)
Selected device. Enabled is not checked.
At checking Enabled, after a second OBS crashed

Workaround is opening OBS Midi Settings in regular mode (not Studio mode). Once a device is enabled, I can switch on and off without crashing in regular or studio mode.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cpyarger** [comment]
Goto Help> Crash reports and upload crash report. and drop that and the log file here please
