### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by torment78** [cpyarger/obs-midi#102]
## Platform
Windows 10
OBS 26.1.1
plugin alpha3.3

there use to be Set preview and set current scene and for some reason they are gone 
is it a bug or is it some thing that should be like that??

**Comment by cpyarger** [comment]
I decided that it made more sense to have them all be under the transition action,

**Comment by cpyarger** [comment]
If need be I could bring back set preview, I just figured having multiple functions for switching things around  is probably overwhelming for alot of people

**Comment by torment78** [comment]
ok i will try it out your way if waas just having a meltdown of sorts its myu the most used function and i thought it was gone after hours of programing bome midi to switch colors :) as long its in there some where im happy since one of the first one i was using untill yesterday cept crashing obs and then it wouldent uninstal .
any way im so happy u guys are working on this plug in its awsome

**Comment by torment78** [comment]
Hi is there a way so that its transition then preview scene  then a specific scene 
so that i press a button and it fires scene one direct to previw 
sorry for my grammar

**Comment by cpyarger** [comment]
I will see about adding back in the "preview scene" action.

**Comment by torment78** [comment]
thank you becouse i have it now setup like this firrst press sends midi on and sets scene 1 as preview second press sends midi off and sets the same scene to ccurrent

**Comment by cpyarger** [comment]
Added back in in the latest release. Found a crash that function was causing and fixed that too
