### ISSUE TITLE
Toggle multiple things with one midi button?

### ISSUE THREAD

**Issue by BeardDesign1** [cpyarger/obs-midi#103]
**Is your feature request related to a problem? Please describe.**
I'm trying to disable one filter and enable another by tapping the same pad, right now I have a workaround using note on for one and note off for the other but it's not ideal, also would like to both switch to a wait scene and mute my mic with one button but again that's not really possible.

**Describe the solution you'd like**
Letting people add multiple actions for the same midi button with the same message type.

**Describe alternatives you've considered**
Maybe having a "Multiple actions" action that opens up a window with gui to add multiple things? that might avoid clogging up the configure tab.

Is that what the macro page is eventually going to be for? If it is and I'm just dumb then ignore this lol

**Comment by cpyarger** [comment]
That is what the macros page will be for (:

**Comment by cpyarger** [comment]
basically the macros page will allow you to build a macro, or multiple action sequence. including adding delays and repeat actions. Right now the macros page is there as a teaser of the upcoming feature. though you shouldnt be able to do anything with it. 

This plus the device feedback mapping system are currently in development on the side. and will be released for test once they are in a working state. 

the idea for the workflow of the macros, is set a macro name, then add multiple actions into the macro, then in the config tab you will see in the actions dropdown a selector for the macros, and another dropdown will appear giving you the current list of macros to choose from.
