### ISSUE TITLE
OBS Crashes on startup

### ISSUE THREAD

**Issue by Dellotek** [cpyarger/obs-midi#108]
OS: Win10 64bit 
OBS Studio 26.1.1. with StreamElements
Installed Version: obs-midi-0.9.3-ALPHA-3.20-Windows-Installer.exe

Errorlog: https://obsproject.com/logs/0gYO4Kd4VXkaY8jc
Log: https://obsproject.com/logs/V9VO5dNp92K_Bjnw

OBS crashed on startup immediately, this problem exist since ALPHA-3.3.
When i go back to obs-midi-d127426 evrything is fine.

**Comment by Dellotek** [comment]
Also with obs-midi 0.9.3-ALPHA-3.25

**Comment by cpyarger** [comment]
Try deleting your config. A couple of the actions have been renamed or merged together . And it seems to cause a crash on startup.  The config is in your obs studio config directory under plugin_config/obs-midi

**Comment by Dellotek** [comment]
I have deleted the config now it works. Thanks 
Now i try to test the new features.
Thanks

**Comment by Dellotek** [comment]
I have deleted the config now it works. Thanks
Now i try to test the new features.
Thanks

**Comment by Dellotek** [comment]
I have deleted the config now it works. 
Now i try to test the new features.
Thanks
