### ISSUE TITLE
MIDI Button Lights ON/OFF

### ISSUE THREAD

**Issue by djtomt1200** [cpyarger/obs-midi#109]
**Describe the solution you'd like**
Option to enable MIDI buttons so when one is triggered "on", it lights up and stays on. When a button is triggered "off" the opposite happens.

**Describe alternatives you've considered**
Tried to modify this in the MIDI controller's editor. Doesn't translate to OBS for some reason.

Operating system and version: Mac OS 10.14.6 Mojave
OBS Studio version: 26.1.2
MIDI Controller: Akai MPK Mini MKII
Pugin Version: obs-midi 0.9.3-ALPHA-3.11

Thank you for your help.

**Comment by cpyarger** [comment]
It still sounds like your buttons are in "momentary" mode not "toggle" mode if they are automatically turning themselves off. 

at some point when the device feedback remapping module has been written, this may be solvable on the obs-midi end. but for now, I would try contacting Akai, I don't currently have one of those devices to test and make fixes with.

**Comment by cpyarger** [comment]
https://inmusicbrands.force.com/akaipro/s/article/Akai-Pro-MPK-mini-mkII-How-to-use-the-Editor

**Comment by djtomt1200** [comment]
Looks like Akai took that option out of the 3rd generation editor for this controller.  It was in the second one.  Very frustrating.  I will wait for the feedback remapping module.  Thanks for your help.
