### ISSUE TITLE
Crashes when a mapping is delted

### ISSUE THREAD

**Issue by AlexanderIsom** [cpyarger/obs-midi#110]
[crash.txt](https://github.com/cpyarger/obs-midi/files/6131923/crash.txt)
## Platform
Operating system and version: windows 10
OBS Studio version: 26.1.1
Midi Controller: korg nanoKontrol2

## Expected Behavior
when a mapping is deleted it should just delete and continue the program

## Current Behavior
sometimes when a mapping is deleted the plugins causes obs to crash

## Steps to Reproduce
1. set up two mappings, one to a button (i used cc 48 the first m key for channel 1) used to toggle the mute state of an audio source, and two the first slider (cc 0) to control the volume of the same audio source, 
2. restart obs, 
3. open the midi obs settings 
4. open the korg configuration 
5. without clicking a mapping, press the delete mapping button, the software will crash

**Comment by cpyarger** [comment]
should be fixed
