### ISSUE TITLE
Launch OBS Scripts

### ISSUE THREAD

**Issue by gdhgdhgdh** [cpyarger/obs-midi#111]
Hello!

I was amazed to find this project and hoped that I'd be able to launch Lua scripts by sending a MIDI message.

I use multiple copies of the [transformer](https://github.com/bromagosa/obs-transformer/blob/master/transformer.lua) script to trigger on-screen animations and I'd love to be able to assign some of these to my Novation Launchpad Mini.

I looked through the actions but couldn't see anything relating to triggering OBS Scripts - is this something you'd consider adding to `obs-midi` ?

Cheers,
Gavin.

**Comment by lorado** [comment]
I also just found this library.
I also would like to have the ability to run OBS Scripts via MIDI Controller (currently using Stream Deck MIDI Button plugin, which controls virtual MIDI device).
I am using modified instant replay script, just for info =)
