### ISSUE TITLE
No LED feedback on midi controller AKAI APCmini

### ISSUE THREAD

**Issue by Zivikiller** [cpyarger/obs-midi#122]
Evertyhing is working fine except the LEDs on my midi device when I active a mapped function.
It doesn't matter which button or with function I mapped.
In general the LEDs are working with other tools.

Operating system and version: Ubuntu 18.4
OBS Studio version: 26.1.1

(this is my first created issue on Github ever !!) yeah :-)
BTW you guys are amazing!! Great work!

**Comment by markbongolan** [comment]
Same midi controller as mine, no led's too

**Comment by cpyarger** [comment]
This is a known issue. And will be taken care of with the feedback mapping system when that is in place. Currently feedback only goes back to the same note or channel messages come in from, and with and the akai devices are more complex then that.
