### ISSUE TITLE
OBS Midi 3.66 Causing Crash on Mac

### ISSUE THREAD

**Issue by djtomt1200** [cpyarger/obs-midi#126]
Updated to the latest version of OBS Midi (3.66) on my MacBook. This causes OBS to crash on opening.  I attempted to install all the available releases down to 3.61. Same issue with all of them.

## Platform
Operating system and version: Mac OS 10.14.6
OBS Studio version: 26.1.1

## Expected Behavior
OBS opens and runs properly after plugin installation

## Current Behavior
After updating to the latest version of the plugin, OBS crashes immediately when attempting to open the program

## Additional information
Crash report attached.
[OBS Crash Report 4-7-2021.pdf](https://github.com/cpyarger/obs-midi/files/6271285/OBS.Crash.Report.4-7-2021.pdf)

**Comment by cpyarger** [comment]
Try deleting your mappings.

**Comment by cpyarger** [comment]
Under the obs config directory is a plugin configs/obs-midi directory the mappings are saved there

**Comment by djtomt1200** [comment]
> Under the obs config directory is a plugin configs/obs-midi directory the mappings are saved there

This worked. I deleted the files and OBS opened. Remapped my controller and everything works fine except for one thing. Every time I close OBS I get a crash message. Crash report attached.

[OBS Crash Report 4-8-21.pdf](https://github.com/cpyarger/obs-midi/files/6278449/OBS.Crash.Report.4-8-21.pdf)

**Comment by djtomt1200** [comment]
> > Under the obs config directory is a plugin configs/obs-midi directory the mappings are saved there
> 
> This worked. I deleted the files and OBS opened. Remapped my controller and everything works fine except for one thing. Every time I close OBS I get a crash message. Crash report attached.
> 
> [OBS Crash Report 4-8-21.pdf](https://github.com/cpyarger/obs-midi/files/6278449/OBS.Crash.Report.4-8-21.pdf)

Update: no longer having this issue. I haven't changed anything. Not sure what happened to take it away.

**Comment by cpyarger** [comment]
the crashing thread is in CRBrowserMain, aka the browser source

**Comment by djtomt1200** [comment]
> the crashing thread is in CRBrowserMain, aka the browser source

I am not using a browser window capture in OBS. I do have a browser open at the same time. Is that what you're talking about? Thanks.

**Comment by LortieGuillaume** [comment]
can anybody point me you the right path to delete the mappings ? 
i cant seems to find it

**Comment by djtomt1200** [comment]
> can anybody point me you the right path to delete the mappings ?
> i cant seems to find it

If you're on a Mac, it's here: ⁨Library⁩ ▸ ⁨Application Support⁩ ▸ ⁨obs-studio⁩ ▸ ⁨plugin_config⁩
