### ISSUE TITLE
OBS-midi.dll not loaded

### ISSUE THREAD

**Issue by LaboratorioGluon** [cpyarger/obs-midi#130]
## Platform
Operating system and version: Windows 10
OBS Studio version: 26.0.2 (64bits)

## Expected Behavior
MIDI plugin in Tools menu

## Current Behavior
OBS-MIDI not loading

## Steps to Reproduce
1. Install OBS
2. Install OBS-MIDI from zip file obs-midi-0.9.3-ALPHA-3.66-Windows.zip
3. MIDI pluging not loaded 
4. See the logs [2021-04-15 14-33-59.txt](https://github.com/Alzy/obs-midi/files/6318003/2021-04-15.14-33-59.txt)

## Additional information
The important part of the log:

```
14:34:01.748: [obs-browser]: Version 2.8.7
14:34:01.758: Module '../../obs-plugins/64bit/obs-midi.dll' not loaded
14:34:02.137: Failed to load 'en-US' text for module: 'soundtrack-plugin.dll'
```

**Comment by cpyarger** [comment]
Use the installer. I can not support people manually installing via the zip /tar.gz files

**Comment by LaboratorioGluon** [comment]
I have tried now with the installer, and still the same issue.
[2021-04-15 17-19-20.txt](https://github.com/cpyarger/obs-midi/files/6319115/2021-04-15.17-19-20.txt)

**Comment by cpyarger** [comment]
Maybe update your obs.  Since you are on 26.0.2 and the latest stable release is 26.1.1

Unfortunately the log file doesn't give any information about why it is not loading the plugin. But the plugin files are seen by obs. Otherwise it wouldn't be mentioning it at all.

**Comment by LaboratorioGluon** [comment]
The problem was the version. Thank you for your support :)
