### ISSUE TITLE
"Do Transition" isn't working in studio mode

### ISSUE THREAD

**Issue by mediacoordinator** [cpyarger/obs-midi#133]
Whenever I create a "Do Transition" action with a specified "Scene" and enter studio mode in OBS it transitions between the "Scene" selected in "Preview" and "Program"

## Platform
Operating system and version: Windows 10 20H2
OBS Studio version: 26.1.1

## Expected Behavior
Triggering midi note should transition the specified "Scene" to "Program"

## Current Behavior
Triggering midi note transitions between the scene selected in "Preview" and "Program"
[2021-05-12 15-49-33.txt](https://github.com/cpyarger/obs-midi/files/6469446/2021-05-12.15-49-33.txt)

## Steps to Reproduce
1. Create "Do Transition" Action and assign it to a midi controller
2. Enter Studio Mode
3. Make sure you're transitioned to any other scene than the one specified in the Action
4. Trigger midi note assigned to "Do Transition"

## Additional information
The functionality works completely ok when not in Studio Mode.
If you would like a video of this bug being replicated then please reach out. At the time of writing this I am unable to. But when I have time I don't mind providing a short video explanation.

**Comment by cpyarger** [comment]
Thank you, II think I know how to fix this, and should have it ready soon.

**Comment by Willyfan** [comment]
Thank you, I found this bug just now and I'm asking what I do wrong...
