### ISSUE TITLE
Trying to assign multiple sounds tracks to the same volume slider. 

### ISSUE THREAD

**Issue by Terence1979** [cpyarger/obs-midi#138]
I am using the midi set up in OBS on my Mac. I am using the APC mini. I have 8 rows with 7 triggers and one volume slider below each of them. I have separate tracks assigned to each trigger that turn on and off just fine. I can assign one track to the volume slider but when I attempt to assign more than one I get a message that says" Can Not Map Channel 0. Please Click Listen One Or Listen Many to listen for MIDI Event to map". after clicking OK I then get another message that says" Mapping already Exists for APC MINI, with channel # 1 norc # 51 and Message type Control Change.  I hope I'm answering you question. thanks again for your help on this

Mac Mini 
BigSur 11.3.1 

Operating system and version:
OBS Studio version: 27.0.1

## Expected Behavior
I should be able to assign more sounds tracks to the same volume slidder.

**Comment by MichaelW1980** [comment]
Are you sure it’s a bug? I’d call this a feature request. But I’m with you, assigning multiple sources to one slider would indeed be very useful!

**Comment by cpyarger** [comment]
This is a core feature. The way the program works does not allow for multiple actions to be tied to one midi message at this time. That will be a part of the upcoming macros system.
