### ISSUE TITLE
APC MINI is not listened / device also used by voicemeeter

### ISSUE THREAD

**Issue by mg56pro** [cpyarger/obs-midi#144]
## Platform

Operating system and version: Win 10 pro v21h1 64b
OBS Studio version:27.0.1 64b

## Expected Behavior
when i click listen one and tap an apc mini key I expected the key to be displayed and ready for mapping

## Current Behavior
the key doesn't display

## Steps to Reproduce
https://youtu.be/MS6nW-xz7p8

1.
2.
3.
4.

## Additional information
some APC MINI keys are already mapped in voicemeeter maybe there's a conflict or voicemeeter has exclusive use . dunno
I used a non mapped key on the video

**Comment by AlexanderIsom** [comment]
Generally with midi devices, only a single application can use the midi device at a time, normally this is a first come first serve, although some applications like midi ox or midi looper can help with this, i don't know if that's the case with the apc mini but I'm using a nonoKontrol2 and it certainly won't work with more than 1 application at a time, also i personally use "listen many" as you can see many changes per channel, this is really helpful for sliders etc ! i'd recommend trying again without voice meter open and seeing / reporting if the bug still persists

**Comment by mg56pro** [comment]
ok ! thx for your reply ^^

**Comment by mg56pro** [comment]
if anyone has the same issue  you can use midi ox and loop midi together to have unlimited apps connected to your midi inputs for free : here's a link https://www.youtube.com/watch?v=B_rYJnTzIC0

hope it can help
