### ISSUE TITLE
Unable to add MIDI signal to action mapping - OS X 11.4 

### ISSUE THREAD

**Issue by jerishsd** [cpyarger/obs-midi#149]
## Platform
Operating system and version: macOS Big Sur 11.4
OBS Studio version: 27.0.1 (mac)

## Expected Behavior
Should be able to add mapping for midi signal to OBS action when clicking Add Mapping button.
Addition to the list pane on top doesn't happen.

## Current Behavior

Nothing happens

## Steps to Reproduce
1. Tools -> OBS Midi Settings
2. Choose MIDI Device in Devices
3. Hit next pane, Configure - <MIDI Device>
4. Change MIDI signal information
5. Choose any OBS action
6. Add mapping

## Additional information
<img width="1003" alt="obs-midi-bug-file" src="https://user-images.githubusercontent.com/306287/130247115-7166efe8-ca92-40b0-aadf-7216591ae947.png">

**Comment by cpyarger** [comment]
You do not change the midi info directly. you use listen one, or listen many to listen to incoming midi messages.
