### ISSUE TITLE
Hotkey does not populate

### ISSUE THREAD

**Issue by leeandron** [cpyarger/obs-midi#156]
## Platform

Operating system and version: Mac OS 11.2
OBS Studio version: 27.1.0 64bit

## Expected Behavior

I should be able to select or type in a hot key to trigger

## Current Behavior

The drop-down is blank. I can't type something in. I'm not sure what else to try.

## Steps to Reproduce

1.(https://user-images.githubusercontent.com/4849296/137976947-52e40962-663b-4469-a4cd-fab954126f73.png)

## Additional information

Thanks so much for working on this. I had tried to map everything out with Midi Loupe and Midi Stroke. I'd love to help, but I'm not sure what else to do.

**Comment by cpyarger** [comment]
It only shows non default hotkeys. Aka ones that come from plugins. Not
built in ones.
