### ISSUE TITLE
Feedback on launcpad buttons

### ISSUE THREAD

**Issue by ghost** [cpyarger/obs-midi#157]
Have the plugin give fedback "colours" on the launchpad ex. Specific scene active, then this button green rest is red.

**Comment by derekbelrose** [comment]
@zybug-dk are you asking for obs-midi to send midi back to the controller so that the button lights up a specific color? If so, I am looking for this as well.

**Comment by AtzinXD** [comment]
es lo mismo que estoy buscando

**Comment by pgScorpio** [comment]
YES! Propper* feedback, especially on current scene and mutes, would be highly appreciated.

* Proper means also update of all scene buttons when the current scene is changed from OBS.

**Comment by Mongstaen** [comment]
Second this!
Feedback to launchpad has been done by this guy previously. Notice that for outer buttons you'll need to define "176" and for inner, "144"

https://github.com/Lexorius/Mairlist-Launchpad-Script

Hope this is to any help.

**Comment by cpyarger** [comment]
There is already a proper feedback mapping system in the works. its taking some time as I am a single developer.  Thanks for the feedback and suggestion.
