### ISSUE TITLE
Delay action after receiving note

### ISSUE THREAD

**Issue by sammallon** [cpyarger/obs-midi#158]
Our system configuration has ~2 seconds of delay between live and when the camera image is rendered. As such, we have configured matching delays on all of our incoming inputs to match the highest latency input. However, the MIDI notes don't have a simple means of adding in arbitrary delay. This means that when MIDI notes are used to switch scenes or perform other actions, they are happening about 2 seconds before we would like them too. Adding in the ability configure either a global or per-note action delay would alleviate this problem, allowing all of our controls to remain synchronized with all of our streams.

**Comment by cpyarger** [comment]
Delays will be an option once I am able to implement the macros system
