### ISSUE TITLE
Mac version do not work/load :-/ 

### ISSUE THREAD

**Issue by jazzcrack** [cpyarger/obs-midi#16]
>OS Version: Version 10.15.7 (Build 19H512)
OBS 26.1.2 (mac)
obs-midi ALPHA 2 2fcf917 AND ALPHA 2 2120725

**Log of OBS with my comments, I hope they are helping:**

> 10:19:18.994: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so->/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so, 257): Library not loaded: /usr/local/opt/jack/lib/libjack.0.dylib

_There is no libjack.0.dylib on this place or on the system. Maybe need to extra installed?_

> 10:19:18.994:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so
10:19:18.994:   Reason: image not found
10:19:18.994: Module '/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so' not loaded

_Wrong location? Maybe /Library/Application\ Support/obs-studio/plugins/obs-midi/bin/obs-midi.so is the right one._

Full log: [2021-02-13 10-19-18.txt](https://github.com/cpyarger/obs-midi/files/5975417/2021-02-13.10-19-18.txt)

**Comment by cpyarger** [comment]
Can you try installing jack?

**Comment by esaiah** [comment]
Hello, thanks for all your hard work!!  The community is super appreciative of all the amazing use they'll get from this midi mapper :)

Unfortunately for me it isn't showing up in tools.  I do see the obs-midi.so file in my Library.  I'm running OSX 10.14.6, and I've restarted since installing.  Would appreciate any suggestions!  Thanks!
Ian

**Comment by cpyarger** [comment]
@esaiah  What version of the plugin are you using? What version of obs?

**Comment by jazzcrack** [comment]
For me it isn't showing up in tools, too.

**Comment by jazzcrack** [comment]
@cpyarger @esaiah After I installed [jack (64bit)](https://jackaudio.org/) it is showing up in tools. I will now try if everything works. Thanks 👍🏻 

Please add the requirement of jack and the step install jack to the documentation. Or did we miss this?

**Comment by cpyarger** [comment]
Updated Documentation in regards to MAC builds in Commit 19d026c
