### ISSUE TITLE
"Toggle Mute" only mutes while button is held.

### ISSUE THREAD

**Issue by Phoenix616** [cpyarger/obs-midi#160]
## Platform

Operating system and version: Windows 10 Pro H21H1 19043.1288
OBS Studio version: 27.1.3 (64 bit)

## Expected Behavior

Pressing a button/key with the "Toggle Mute" action 

## Current Behavior

When using the touch pads of a LaunchKey Mini MK3 to execute the "Toggle Mute" action it will only mute (or unmute) as long as the button is held. I doubt this is the expected behaviour of that action, "toggling" sounds like it should switch between mute and unmuting when the button is pressed. (If I wanted it to do that automatically I would put another toggle mute action on the "Note Off" Message Type)

[Log file](https://obsproject.com/logs/msMDJA1EAeRzm2u_)

## Steps to Reproduce

1. Configure a key with the "Toggle Mute" action for an audio source
2. Press and release it
3. Audio source mutes on press and unmutes on release

## Additional information

This behaviour might be specific to the LaunchKeys, not sure.

**Comment by cpyarger** [comment]
Edit your button in launch keys to be a toggle button, not momentary. 

a quick search pulls up this 

https://support.novationmusic.com/hc/en-gb/articles/360014619639-Components-Launchkey-MK3-Template-Editor-Guide

**Comment by Phoenix616** [comment]
Oh, didn't know that was done via the firmware directly. Thanks for pointing that one out.

**Comment by cpyarger** [comment]
No problem, Most modern midi boards let one modify the behaviors of the buttons, faders and knobs.

**Comment by Phoenix616** [comment]
Unfortunately it looks like changing that is either not supported for the one I have or they removed that feature in some update (I actually had an older version of Components installed which provided that option but didn't have support for the Mini MK3, updating added support but [no longer shows the option](https://i.moep.tv/gij0rNqP.png)) so I guess I have to talk to them and if they really don't support that I try to find my own solution or modify this plugin/ask for that as a feature of you and hope.
