### ISSUE TITLE
Reading MIDI signals from /dev/snd/seq

### ISSUE THREAD

**Issue by dabruh** [cpyarger/obs-midi#161]
**Is your feature request related to a problem? Please describe.**
I'm using an application called TouchOSC which sends signals using TCP/IP. The TouchOSC bridge allows converting these signals to MIDI, and there is a community effort to support Linux called [touchosc2midi](https://github.com/velolala/touchosc2midi). I'm running touchosc2midi using Docker and it works well as I can use the signals in Jack/Carla.

**Describe the solution you'd like**
touchosc2midi outputs MIDI signals to /dev/snd/seq and it would be really nice of obs-midi was able to read from here - or perhaps if someone is able to provide a workaround on how to create a virtual hardware device which sends I/O to /dev/snd/seq

**Comment by cpyarger** [comment]
I am using the libremidi library for midi interfacing. I would recommend
posting there.

https://github.com/jcelerier/libremidi
