### ISSUE TITLE
Source code: out-of-date / won't build?

### ISSUE THREAD

**Issue by gee-ell** [cpyarger/obs-midi#162]
obs-midi is so useful, but it seems like it's no longer maintained?

I'd like to get the source compiling so I can add or fix things if needed.  I managed to integrate the current GitHub source into my MSCV obs-studio build (using the provided instructions), but it seems to be out-of-date, missing basic features including even a functioning 'Add Mapping' button.

I then tried to copy the source code files from the .zip released with the latest binary, but that fails to build with errors in moc_ files, eg. unknown symbol 'MidiMapping' (I don't understand how this works, but I assume it's something to do with QT?).  Anybody get this working?

**Comment by gee-ell** [comment]
.. should I be using a specific branch and not master?

BTW, this build instruction was wrong for me:

"add_subdirectory(**obs-midi**)"

I had to use "add_subdirectory(**plugins/obs-midi**)"

**Comment by cpyarger** [comment]
> .. should I be using a specific branch and not master?
> 
> BTW, this build instruction was wrong for me:
> 
> "add_subdirectory(**obs-midi**)"
> 
> I had to use "add_subdirectory(**plugins/obs-midi**)"

no, it's not wrong, you added the line to the wrong CMakeLists.txt file. it should be the one in the plugins directory, NOT the top directory. 

Also, I am currently working on the Actions branch. There is a bit of reworking of things that had the code broken for a bit.
