### ISSUE TITLE
Assigning fader to move transition bar works randomly

### ISSUE THREAD

**Issue by neozhen** [cpyarger/obs-midi#168]
## Platform

Operating system and version: windows 10 pro 21h2
OBS Studio version: 27.1.3

## Expected Behavior

When i assign a fader to move transition bar i will change from Source A to B and after from B to A, i.e with Fade transition. Even stay at 50/60 or whetever percentage i want between both sources.

## Current Behavior

If i select a fader to move transition bar the transition works ok for A to B but when i try to go from B to A after the first time i move the fader, the image changes to A by cut instead of transition assigned i.e fade, and then starts transitioning from A to B to A and randomly ends on A or B and in time to time both the preview and the program audio are running on Program.

20:50:29.246: CPU Name: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
20:50:29.246: CPU Speed: 2926MHz
20:50:29.246: Physical Cores: 4, Logical Cores: 8
20:50:29.246: Physical Memory: 8125MB Total, 4366MB Free
20:50:29.246: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1415; 64-bit)
20:50:29.246: Running as administrator: false
20:50:29.246: Aero is Enabled (Aero is always on for windows 8 and above)
20:50:29.246: Windows 10 Gaming Features:
20:50:29.246: 	Game DVR: On
20:50:29.248: Sec. Software Status:
20:50:29.250: 	Antivirus de Microsoft Defender: enabled (AV)
20:50:29.250: 	Firewall de Windows: enabled (FW)
20:50:29.251: Current Date/Time: 2021-12-21, 20:50:29
20:50:29.251: Browser Hardware Acceleration: true
20:50:29.251: Portable mode: false
20:50:29.716: OBS 27.1.3 (64-bit, windows)
20:50:29.716: ---------------------------------
20:50:29.772: ---------------------------------
20:50:29.772: audio settings reset:
20:50:29.772: 	samples per sec: 48000
20:50:29.772: 	speakers:        2
20:50:29.774: ---------------------------------
20:50:29.774: Initializing D3D11...
20:50:29.774: Available Video Adapters: 
20:50:29.776: 	Adapter 0: NVIDIA GeForce GTX 460
20:50:29.776: 	  Dedicated VRAM: 1016266752
20:50:29.776: 	  Shared VRAM:    4260036608
20:50:29.776: 	  PCI ID:         10de:e22
20:50:29.777: 	  Driver Version: 23.21.13.9135
20:50:29.777: 	  output 0: pos={0, 0}, size={1360, 768}, attached=true, refresh=60, name=SAMSUNG
20:50:29.780: Loading up D3D11 on adapter NVIDIA GeForce GTX 460 (0)
20:50:29.864: D3D11 loaded successfully, feature level used: b000
20:50:29.864: DXGI increase maximum frame latency success
20:50:29.864: D3D11 GPU priority setup failed (not admin?)
20:50:30.454: ---------------------------------
20:50:30.454: video settings reset:
20:50:30.454: 	base resolution:   1280x720
20:50:30.454: 	output resolution: 1280x720
20:50:30.454: 	downscale filter:  Bicubic
20:50:30.454: 	fps:               30000/1001
20:50:30.454: 	format:            NV12
20:50:30.454: 	YUV mode:          709/Full
20:50:30.454: NV12 texture support enabled
20:50:30.455: Audio monitoring device:
20:50:30.455: 	name: Por defecto
20:50:30.455: 	id: default
20:50:30.456: ---------------------------------
20:50:30.456: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
20:50:30.461: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
20:50:30.462: Failed to load 'en-US' text for module: 'decklink-captions.dll'
20:50:30.463: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
20:50:30.508: [AMF] Unable to load 'amfrt64.dll', error code 126.
20:50:30.510: [AMF] AMF Test failed due to one or more errors.
20:50:30.510: Failed to initialize module 'enc-amf.dll'
20:50:30.523: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
20:50:30.529: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
20:50:30.530: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
20:50:30.537: [obs-browser]: Version 2.16.3
20:50:30.537: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
20:50:30.543: LoadLibrary failed for 'nvEncodeAPI64.dll': (null) (126)
20:50:30.545: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
20:50:30.548: [obs-midi] MIDI LOADED! :)
20:50:30.548: [obs-midi] obs-midi version 
20:50:30.575: [obs-midi] UNLOADING DEVICE MANAGER
20:50:30.575: [obs-midi] UNLOADING DEVICE MANAGER
20:50:30.576: [obs-midi] UNLOADING DEVICE MANAGER
20:50:30.577: [obs-midi] MIDI device connected In: [0] nanoKONTROL2 1
20:50:30.685: [obs-ndi] hello ! (version 4.9.0)
20:50:30.685: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Tools\Runtime'
20:50:30.685: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Tools/Runtime/Processing.NDI.Lib.x64.dll'
20:50:30.689: [obs-ndi] NDI runtime loaded successfully
20:50:30.698: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 01:27:52 Sep 10 2020 4.5.3.0)
20:50:30.801: [obs-websocket] you can haz websockets (version 4.9.1)
20:50:30.801: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.2
20:50:30.803: [obs-websocket] module loaded!
20:50:30.814: VLC found, VLC video source enabled
20:50:30.823: Decklink API Compiled version 11.6
20:50:30.823: Decklink API Installed version 12.0
20:50:30.840: ---------------------------------
20:50:30.840:   Loaded Modules:
20:50:30.840:     obs-multi-rtmp.dll
20:50:30.840:     win-wasapi.dll
20:50:30.840:     win-mf.dll
20:50:30.840:     win-dshow.dll
20:50:30.840:     win-decklink.dll
20:50:30.840:     win-capture.dll
20:50:30.840:     vlc-video.dll
20:50:30.840:     text-freetype2.dll
20:50:30.840:     rtmp-services.dll
20:50:30.840:     obs-x264.dll
20:50:30.840:     obs-websocket.dll
20:50:30.840:     obs-vst.dll
20:50:30.840:     obs-transitions.dll
20:50:30.840:     obs-text.dll
20:50:30.840:     obs-qsv11.dll
20:50:30.840:     obs-outputs.dll
20:50:30.840:     obs-ndi.dll
20:50:30.840:     obs-midi.dll
20:50:30.840:     obs-filters.dll
20:50:30.840:     obs-ffmpeg.dll
20:50:30.840:     obs-browser.dll
20:50:30.840:     image-source.dll
20:50:30.840:     frontend-tools.dll
20:50:30.840:     enc-amf.dll
20:50:30.840:     decklink-ouput-ui.dll
20:50:30.840:     decklink-captions.dll
20:50:30.840:     coreaudio-encoder.dll
20:50:30.840: ---------------------------------
20:50:30.840: ==== Startup complete ===============================================
20:50:30.861: Switched to Preview/Program mode
20:50:30.861: ------------------------------------------------
20:50:30.870: All scene data cleared
20:50:30.870: ------------------------------------------------
20:50:30.962: [Media Source 'Laura.mp4']: settings:
20:50:30.962: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/Laura.mp4
20:50:30.962: 	input_format:            (null)
20:50:30.962: 	speed:                   100
20:50:30.962: 	is_looping:              no
20:50:30.962: 	is_linear_alpha:         no
20:50:30.962: 	is_hw_decoding:          no
20:50:30.962: 	is_clear_on_media_end:   no
20:50:30.962: 	restart_on_activate:     yes
20:50:30.962: 	close_when_inactive:     no
20:50:30.997: [Media Source '1-El dolor de la soledad.mp4']: settings:
20:50:30.997: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/Videoclip El dolor de la soledad.mp4
20:50:30.997: 	input_format:            (null)
20:50:30.997: 	speed:                   100
20:50:30.997: 	is_looping:              no
20:50:30.997: 	is_linear_alpha:         no
20:50:30.997: 	is_hw_decoding:          no
20:50:30.997: 	is_clear_on_media_end:   no
20:50:30.997: 	restart_on_activate:     yes
20:50:30.997: 	close_when_inactive:     no
20:50:31.007: [Media Source '3-No consigo amarte.mp4']: settings:
20:50:31.007: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/No consigo amarte.mp4
20:50:31.007: 	input_format:            (null)
20:50:31.007: 	speed:                   100
20:50:31.007: 	is_looping:              no
20:50:31.007: 	is_linear_alpha:         no
20:50:31.007: 	is_hw_decoding:          no
20:50:31.007: 	is_clear_on_media_end:   no
20:50:31.007: 	restart_on_activate:     yes
20:50:31.007: 	close_when_inactive:     no
20:50:31.008: [Media Source '4-Love.mp4']: settings:
20:50:31.008: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/Love.mp4
20:50:31.008: 	input_format:            (null)
20:50:31.008: 	speed:                   100
20:50:31.008: 	is_looping:              no
20:50:31.008: 	is_linear_alpha:         no
20:50:31.008: 	is_hw_decoding:          no
20:50:31.008: 	is_clear_on_media_end:   no
20:50:31.008: 	restart_on_activate:     yes
20:50:31.008: 	close_when_inactive:     no
20:50:31.027: [Media Source '2-Como decirte.mp4']: settings:
20:50:31.027: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/Como decirte.mp4
20:50:31.027: 	input_format:            (null)
20:50:31.027: 	speed:                   100
20:50:31.027: 	is_looping:              no
20:50:31.027: 	is_linear_alpha:         no
20:50:31.027: 	is_hw_decoding:          no
20:50:31.027: 	is_clear_on_media_end:   no
20:50:31.027: 	restart_on_activate:     yes
20:50:31.027: 	close_when_inactive:     no
20:50:31.094: [Media Source 'WhatsApp Video 2021-12-16 at 14.03.55.mp4']: settings:
20:50:31.094: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/WhatsApp Video 2021-12-16 at 14.03.55.mp4
20:50:31.094: 	input_format:            (null)
20:50:31.094: 	speed:                   100
20:50:31.094: 	is_looping:              no
20:50:31.094: 	is_linear_alpha:         no
20:50:31.094: 	is_hw_decoding:          no
20:50:31.094: 	is_clear_on_media_end:   yes
20:50:31.094: 	restart_on_activate:     yes
20:50:31.094: 	close_when_inactive:     no
20:50:31.150: [Media Source 'rumbeando.mp4']: settings:
20:50:31.150: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/Rumbeando ok.mp4
20:50:31.150: 	input_format:            (null)
20:50:31.150: 	speed:                   100
20:50:31.150: 	is_looping:              no
20:50:31.150: 	is_linear_alpha:         no
20:50:31.150: 	is_hw_decoding:          no
20:50:31.150: 	is_clear_on_media_end:   no
20:50:31.150: 	restart_on_activate:     yes
20:50:31.150: 	close_when_inactive:     no
20:50:31.171: [Media Source 'loop yc.mp4 (2)']: settings:
20:50:31.171: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/loop yc.mp4
20:50:31.171: 	input_format:            (null)
20:50:31.171: 	speed:                   100
20:50:31.171: 	is_looping:              no
20:50:31.171: 	is_linear_alpha:         no
20:50:31.171: 	is_hw_decoding:          no
20:50:31.171: 	is_clear_on_media_end:   no
20:50:31.171: 	restart_on_activate:     yes
20:50:31.171: 	close_when_inactive:     no
20:50:31.185: [Media Source '00-festival apertura.mp4']: settings:
20:50:31.185: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/apertura 2021.mov
20:50:31.185: 	input_format:            (null)
20:50:31.185: 	speed:                   100
20:50:31.185: 	is_looping:              no
20:50:31.185: 	is_linear_alpha:         no
20:50:31.185: 	is_hw_decoding:          no
20:50:31.185: 	is_clear_on_media_end:   no
20:50:31.185: 	restart_on_activate:     yes
20:50:31.185: 	close_when_inactive:     no
20:50:31.186: [Media Source '00-festival cierre.mp4']: settings:
20:50:31.186: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/00-festival cierre.mp4
20:50:31.186: 	input_format:            (null)
20:50:31.186: 	speed:                   100
20:50:31.186: 	is_looping:              no
20:50:31.186: 	is_linear_alpha:         no
20:50:31.186: 	is_hw_decoding:          no
20:50:31.186: 	is_clear_on_media_end:   no
20:50:31.186: 	restart_on_activate:     yes
20:50:31.186: 	close_when_inactive:     no
20:50:31.186: [Media Source '00-ZOCALO inferior derecho ALPHA.mov']: settings:
20:50:31.186: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/00-ZOCALO inferior derecho ALPHA.mov
20:50:31.186: 	input_format:            (null)
20:50:31.186: 	speed:                   100
20:50:31.186: 	is_looping:              no
20:50:31.186: 	is_linear_alpha:         no
20:50:31.186: 	is_hw_decoding:          no
20:50:31.186: 	is_clear_on_media_end:   yes
20:50:31.186: 	restart_on_activate:     yes
20:50:31.186: 	close_when_inactive:     no
20:50:31.187: [Media Source 'caja navideña.mp4']: settings:
20:50:31.187: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/caja navideña.mp4
20:50:31.187: 	input_format:            (null)
20:50:31.187: 	speed:                   100
20:50:31.187: 	is_looping:              no
20:50:31.187: 	is_linear_alpha:         no
20:50:31.187: 	is_hw_decoding:          no
20:50:31.187: 	is_clear_on_media_end:   no
20:50:31.187: 	restart_on_activate:     yes
20:50:31.187: 	close_when_inactive:     no
20:50:31.239: [Media Source 'dona pan dulce.mp4']: settings:
20:50:31.239: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/dona pan dulce.mp4
20:50:31.239: 	input_format:            (null)
20:50:31.239: 	speed:                   100
20:50:31.239: 	is_looping:              no
20:50:31.239: 	is_linear_alpha:         no
20:50:31.239: 	is_hw_decoding:          no
20:50:31.239: 	is_clear_on_media_end:   no
20:50:31.239: 	restart_on_activate:     yes
20:50:31.239: 	close_when_inactive:     no
20:50:31.267: [Media Source 'donar 2.mp4']: settings:
20:50:31.267: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/donar 2.mp4
20:50:31.267: 	input_format:            (null)
20:50:31.267: 	speed:                   100
20:50:31.267: 	is_looping:              no
20:50:31.267: 	is_linear_alpha:         no
20:50:31.267: 	is_hw_decoding:          no
20:50:31.267: 	is_clear_on_media_end:   no
20:50:31.267: 	restart_on_activate:     yes
20:50:31.267: 	close_when_inactive:     no
20:50:31.283: [Media Source 'Donar.mp4']: settings:
20:50:31.283: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/Donar.mp4
20:50:31.283: 	input_format:            (null)
20:50:31.283: 	speed:                   100
20:50:31.283: 	is_looping:              no
20:50:31.283: 	is_linear_alpha:         no
20:50:31.283: 	is_hw_decoding:          no
20:50:31.283: 	is_clear_on_media_end:   no
20:50:31.283: 	restart_on_activate:     yes
20:50:31.283: 	close_when_inactive:     no
20:50:31.657: [Media Source 'voluntario.mp4']: settings:
20:50:31.657: 	input:                   D:/WORKING PROGRESS/Lumen Cor/2021/voluntario.mp4
20:50:31.657: 	input_format:            (null)
20:50:31.657: 	speed:                   100
20:50:31.657: 	is_looping:              no
20:50:31.657: 	is_linear_alpha:         no
20:50:31.657: 	is_hw_decoding:          no
20:50:31.657: 	is_clear_on_media_end:   no
20:50:31.657: 	restart_on_activate:     yes
20:50:31.657: 	close_when_inactive:     no
20:50:31.669: [Media Source 'AMAR NO ES playback.wav']: settings:
20:50:31.669: 	input:                   D:/WORKING PROGRESS/Lumen Cor/AMAR NO ES playback.wav
20:50:31.669: 	input_format:            (null)
20:50:31.669: 	speed:                   100
20:50:31.669: 	is_looping:              no
20:50:31.669: 	is_linear_alpha:         no
20:50:31.669: 	is_hw_decoding:          no
20:50:31.669: 	is_clear_on_media_end:   no
20:50:31.669: 	restart_on_activate:     yes
20:50:31.669: 	close_when_inactive:     no
20:50:31.748: Switched to scene 'VIDEOS JORGE'
20:50:31.751: ------------------------------------------------
20:50:31.751: Loaded scenes:
20:50:31.751: - scene 'YA COM':
20:50:31.751:     - source: 'loop yc.mp4 (2)' (ffmpeg_source)
20:50:31.751:         - monitoring: monitor and output
20:50:31.751: - scene 'APERTURA':
20:50:31.751:     - source: 'AMAR NO ES playback.wav' (ffmpeg_source)
20:50:31.751:         - monitoring: monitor and output
20:50:31.751:     - source: '00-festival apertura.mp4' (ffmpeg_source)
20:50:31.751:     - source: 'WhatsApp Video 2021-12-16 at 14.03.55.mp4' (ffmpeg_source)
20:50:31.751:         - monitoring: monitor and output
20:50:31.751: - scene 'JORGEE':
20:50:31.751:     - source: '00-ZOCALO inferior derecho ALPHA.mov' (ffmpeg_source)
20:50:31.751:     - source: 'ZOC donaahora.png' (image_source)
20:50:31.751:     - source: 'ZOC ARI VAAMONDE.png' (image_source)
20:50:31.751:     - source: 'ZOC jorgevega.png' (image_source)
20:50:31.751:     - source: 'ZOC juanignaciootero.png' (image_source)
20:50:31.751:     - source: 'ZOC lauraalbarracin.png' (image_source)
20:50:31.751:     - source: 'MOSCA.png' (image_source)
20:50:31.751: - scene 'VIDEOS JORGE':
20:50:31.751:     - source: '4-Love.mp4' (ffmpeg_source)
20:50:31.751:         - monitoring: monitor and output
20:50:31.751:     - source: '3-No consigo amarte.mp4' (ffmpeg_source)
20:50:31.751:     - source: '2-Como decirte.mp4' (ffmpeg_source)
20:50:31.751:         - monitoring: monitor and output
20:50:31.751:     - source: '1-El dolor de la soledad.mp4' (ffmpeg_source)
20:50:31.751:         - monitoring: monitor and output
20:50:31.751:     - source: 'ZOC JORGE YOUTUBE.png' (image_source)
20:50:31.751: - scene 'PABLOO':
20:50:31.751:     - source: 'PABLO' (browser_source)
20:50:31.752:     - source: 'ZOC PABLO GAIAZZI.png' (image_source)
20:50:31.752:     - source: 'MOSCA.png' (image_source)
20:50:31.752: - scene 'DUPLEX':
20:50:31.752:     - source: 'fondo duplex.png' (image_source)
20:50:31.752:     - source: 'JORGE' (browser_source)
20:50:31.752:     - source: 'PABLO' (browser_source)
20:50:31.752:     - source: 'JUAN IGNACIO' (browser_source)
20:50:31.752:     - source: 'JUAN' (browser_source)
20:50:31.752: - scene 'JUAN JAFELLA':
20:50:31.752:     - source: 'JUAN' (browser_source)
20:50:31.752:     - source: 'ZOC juanignaciojafella.png' (image_source)
20:50:31.752:     - source: 'MOSCA.png' (image_source)
20:50:31.752: - scene 'MATII':
20:50:31.752:     - source: 'MATIAS' (browser_source)
20:50:31.752:     - source: 'ZOC matiasbeledo.png' (image_source)
20:50:31.752:     - source: 'MOSCA.png' (image_source)
20:50:31.752: - scene 'JUANIII':
20:50:31.752:     - source: 'JUAN IGNACIO' (browser_source)
20:50:31.752:     - source: 'ZOC juanignaciootero.png' (image_source)
20:50:31.752:     - source: 'MOSCA.png' (image_source)
20:50:31.752: - scene 'TRIPLEX':
20:50:31.752:     - source: 'fondo duplex.png' (image_source)
20:50:31.752:     - source: 'JORGE' (browser_source)
20:50:31.752:     - source: 'PABLO' (browser_source)
20:50:31.752:     - source: 'JUAN IGNACIO' (browser_source)
20:50:31.752: - scene 'SEPARADORES':
20:50:31.752:     - source: 'voluntario.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752:     - source: 'dona pan dulce.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752:     - source: 'donar 2.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752:     - source: 'Donar.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752:     - source: 'caja navideña.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752: - scene 'RUMBEANDO':
20:50:31.752:     - source: 'rumbeando.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752: - scene 'LAURA':
20:50:31.752:     - source: 'Laura.mp4' (ffmpeg_source)
20:50:31.752:         - monitoring: monitor and output
20:50:31.752: - scene 'QUAD':
20:50:31.752:     - source: 'fondo duplex.png' (image_source)
20:50:31.753:     - source: 'Origen de color' (color_source_v3)
20:50:31.753:     - source: 'JORGE' (browser_source)
20:50:31.753:     - source: 'PABLO' (browser_source)
20:50:31.753:     - source: 'JUAN IGNACIO' (browser_source)
20:50:31.753:     - source: 'JUAN' (browser_source)
20:50:31.753: - scene 'CIERRE':
20:50:31.753:     - source: 'AMAR NO ES playback.wav' (ffmpeg_source)
20:50:31.753:         - monitoring: monitor and output
20:50:31.753:     - source: '00-festival cierre.mp4' (ffmpeg_source)
20:50:31.753: ------------------------------------------------
20:50:32.073: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
20:50:32.073: [obs-websocket] server started successfully on port 4444
20:50:32.073: [obs-websocket] IO thread started.
20:50:38.004: [obs-midi] Item enabled: nanoKONTROL2 1
20:51:46.847: adding 341 milliseconds of audio buffering, total audio buffering is now 341 milliseconds (source: 2-Como decirte.mp4)
20:51:46.847: 
21:01:07.650: ==== Shutting down ==================================================
21:01:07.862: All scene data cleared
21:01:07.862: ------------------------------------------------
21:01:07.863: [obs-websocket] IO thread exited.
21:01:07.863: [obs-websocket] server stopped successfully
21:01:08.000: [obs-websocket] goodbye!
21:01:08.002: [obs-ndi] goodbye !
21:01:08.005: [obs-midi] UNLOADING DEVICE MANAGER
21:01:08.052: [Scripting] Total detached callbacks: 0
21:01:08.052: Freeing OBS context data
21:01:08.082: == Profiler Results =============================
21:01:08.082: run_program_init: 2892.69 ms
21:01:08.082:  ┣OBSApp::AppInit: 26.805 ms
21:01:08.082:  ┃ ┗OBSApp::InitLocale: 4.759 ms
21:01:08.082:  ┗OBSApp::OBSInit: 2828.76 ms
21:01:08.082:    ┣obs_startup: 5.408 ms
21:01:08.082:    ┗OBSBasic::OBSInit: 2302.83 ms
21:01:08.082:      ┣OBSBasic::InitBasicConfig: 0.942 ms
21:01:08.082:      ┣OBSBasic::ResetAudio: 0.273 ms
21:01:08.082:      ┣OBSBasic::ResetVideo: 682.808 ms
21:01:08.082:      ┣OBSBasic::InitOBSCallbacks: 0.008 ms
21:01:08.082:      ┣OBSBasic::InitHotkeys: 0.058 ms
21:01:08.082:      ┣obs_load_all_modules: 383.855 ms
21:01:08.082:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 1.912 ms
21:01:08.082:      ┃ ┣obs_init_module(decklink-captions.dll): 0.029 ms
21:01:08.082:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.804 ms
21:01:08.082:      ┃ ┣obs_init_module(enc-amf.dll): 43.993 ms
21:01:08.082:      ┃ ┣obs_init_module(frontend-tools.dll): 6.417 ms
21:01:08.082:      ┃ ┣obs_init_module(image-source.dll): 0.008 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-browser.dll): 0.41 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 1.455 ms
21:01:08.082:      ┃ ┃ ┗nvenc_check: 1.438 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-filters.dll): 0.074 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-midi.dll): 134.097 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-ndi.dll): 30.972 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-outputs.dll): 0.013 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-qsv11.dll): 69.002 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-text.dll): 0.349 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-transitions.dll): 0.007 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-vst.dll): 0.001 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-websocket.dll): 2.335 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-x264.dll): 0.002 ms
21:01:08.082:      ┃ ┣obs_init_module(rtmp-services.dll): 0.656 ms
21:01:08.082:      ┃ ┣obs_init_module(text-freetype2.dll): 0.085 ms
21:01:08.082:      ┃ ┣obs_init_module(vlc-video.dll): 1.837 ms
21:01:08.082:      ┃ ┣obs_init_module(win-capture.dll): 2.205 ms
21:01:08.082:      ┃ ┣obs_init_module(win-decklink.dll): 6.227 ms
21:01:08.082:      ┃ ┣obs_init_module(win-dshow.dll): 1.879 ms
21:01:08.082:      ┃ ┣obs_init_module(win-mf.dll): 0 ms
21:01:08.082:      ┃ ┣obs_init_module(win-wasapi.dll): 0.008 ms
21:01:08.082:      ┃ ┣obs_init_module(obs-multi-rtmp.dll): 3.898 ms
21:01:08.082:      ┃ ┗reset_win32_symbol_paths: 0.34 ms
21:01:08.082:      ┣OBSBasic::ResetOutputs: 0.353 ms
21:01:08.082:      ┣OBSBasic::CreateHotkeys: 0.054 ms
21:01:08.082:      ┣OBSBasic::InitService: 2.242 ms
21:01:08.082:      ┣OBSBasic::InitPrimitives: 0.164 ms
21:01:08.082:      ┗OBSBasic::Load: 916.707 ms
21:01:08.082: obs_hotkey_thread(25 ms): min=0.004 ms, median=0.013 ms, max=17.165 ms, 99th percentile=0.087 ms, 100% below 25 ms
21:01:08.082: audio_thread(Audio): min=0 ms, median=0.049 ms, max=8.319 ms, 99th percentile=0.204 ms
21:01:08.082: obs_graphics_thread(33.3667 ms): min=0.085 ms, median=0.794 ms, max=812.547 ms, 99th percentile=1.841 ms, 99.9948% below 33.367 ms
21:01:08.082:  ┣tick_sources: min=0.001 ms, median=0.023 ms, max=812.358 ms, 99th percentile=0.143 ms
21:01:08.082:  ┣output_frame: min=0.06 ms, median=0.337 ms, max=9.41 ms, 99th percentile=1.298 ms
21:01:08.082:  ┃ ┗gs_context(video->graphics): min=0.06 ms, median=0.336 ms, max=9.409 ms, 99th percentile=1.297 ms
21:01:08.082:  ┃   ┣render_video: min=0.004 ms, median=0.03 ms, max=8.71 ms, 99th percentile=1.1 ms
21:01:08.082:  ┃   ┃ ┗render_main_texture: min=0.003 ms, median=0.028 ms, max=8.706 ms, 99th percentile=1.095 ms
21:01:08.082:  ┃   ┗gs_flush: min=0.055 ms, median=0.251 ms, max=0.992 ms, 99th percentile=0.402 ms
21:01:08.082:  ┗render_displays: min=0.001 ms, median=0.118 ms, max=16.746 ms, 99th percentile=0.842 ms
21:01:08.082: =================================================
21:01:08.082: == Profiler Time Between Calls ==================
21:01:08.082: obs_hotkey_thread(25 ms): min=24.255 ms, median=25.92 ms, max=44.663 ms, 44.7805% within ±2% of 25 ms (0.00800224% lower, 55.2115% higher)
21:01:08.082: obs_graphics_thread(33.3667 ms): min=21.609 ms, median=33.367 ms, max=812.556 ms, 99.8638% within ±2% of 33.367 ms (0.0733637% lower, 0.0628832% higher)
21:01:08.082: =================================================
21:01:08.115: Number of memory leaks: 0

## Steps to Reproduce

https://drive.google.com/file/d/1inZm1feiSBPAMELAQ77BK5mkbwcneB5B/view?usp=sharing

1.
2.
3.
4.

**Comment by cpyarger** [comment]
This is a known issue, Also its not random,  just repeatable unexpected behavior.  I had to wait for the obs project to implement some changes I made in the API, within the next release or two of the plugin I should have proper feedback from the t-bar which should eliminate this issue
