### ISSUE TITLE
Can't detect every hotkey

### ISSUE THREAD

**Issue by chinzistor** [cpyarger/obs-midi#170]
Operating system and version: Ubuntu 20.04.3 LTS
OBS Studio version: 27.1.3 (64 bit)

Detection of hotkeys is incomplete. I'm using an external Python script to trigger commands on my Twitch chat using hotkeys, but OBS Midi detects only 1 hotkey from the list (which works fine). Manually editing the settings file doesn't work either.

I'm using OBS ChatSpam for the extra hotkeys, after setting that up, I tried binding buttons on my Midi controller to these new hotkeys, but I see only one of them in the list.
![Screenshot from 2022-01-21 22-28-26](https://user-images.githubusercontent.com/36666277/150603301-0cdac9f0-f05b-46ef-abdb-21b535f0a77a.png)
![Screenshot from 2022-01-21 22-28-57](https://user-images.githubusercontent.com/36666277/150603306-5effb806-eb8d-47e4-af63-0a01cbbf28d4.png)

**Comment by cpyarger** [comment]
The program currently only detects hotkeys that are registered via the obs API, I have not used the python script  you mentioned.  and it will be a while before I am done with the current rewrite that I am working on.  I would suggest looking at the python script and seeing if it is registering all of the hotkeys properly. 

also, as a side note, you do not need to actually set a hotkey to have a keycombo in order for obs-midi to see and use it :smile_cat: 

take a look here for more info on scripts that register hotkeys 

https://github.com/cpyarger/obs-midi/pull/115#issuecomment-798780575
