### ISSUE TITLE
Add Export/Import mapping settings

### ISSUE THREAD

**Issue by andrestelex** [cpyarger/obs-midi#172]
Problem:
OSX: When changing Scene collection or Profiles some crashes happened and the mapping settings get lost

Solution:
Ability to import/export mapping to/from external files. That will provide more confidence if the system is unstable and there is a potential risk of data loss. Also provide users with a backup and alternative config feature.

**Comment by cpyarger** [comment]
So, all config files are available in the plugin_config folder. We dont and wont be supporting exporting and importing these files, as a single change in obs can invalidate them. for example backup the file then delete a source, OBS will crash when you try to execute an action on that source. 


also, 

scene collections, and profiles are already added to the naming convention of the config JSON files.  so when you change scene collections or profiles, your mappings should be cleared and reloaded. 

Please Note, 

While you CAN mess with the config files directly, it is highly recommended you don't. we cant support anyone who does so. (:
