### ISSUE TITLE
Program Change message specifics not detected

### ISSUE THREAD

**Issue by ericfont** [cpyarger/obs-midi#20]
I'm on latest obs-midi ALPHA 2 f065c36 on windows (https://github.com/cpyarger/obs-midi/tree/tag-f065c36).

Using the "Listen One/Many" feature, obs-midi is able to detect me initiating a program change message from my midi device.  However obs-midi does not detect the specific contents of that program change message, but rather simply seems to simply use 127 for note/control and value and doesn't even update the "Message Type" drop-down box.

(I can listen for note on and note off and control change events fine.)

**Comment by cpyarger** [comment]
Yes, I haven't finished the code for handling program changes yet.  it is definitely in the works

**Comment by cpyarger** [comment]
Added and Working in #26
