### ISSUE TITLE
Clean up memory leaks

### ISSUE THREAD

**Issue by cpyarger** [cpyarger/obs-midi#25]
There are a large number of memory leaks in the code, And I will be the first to admit I am a bit lost when trying to deal with them. Any help would be greatly appreciated!

**Comment by ericfont** [comment]
do you know how to use Valgrind's Memcheck tool to find memory leaks? https://doc.qt.io/qtcreator/creator-analyzer.html

**Comment by cpyarger** [comment]
No, unfortunately, it is something beyond my skill level.

**Comment by ericfont** [comment]
ok, well if I can make some time I'll try to look into it.

**Comment by cpyarger** [comment]
Thanks! Appreciated!
