### ISSUE TITLE
OBS crashing when enabling device

### ISSUE THREAD

**Issue by PSurmon** [cpyarger/obs-midi#28]
Good day

Thanks for the add-on, however every time I enable my device (Korg nano PAD2) OBS crashes. It is quite possible I have done something wrong on my end, please help when you have a moment.

Many thanks

Peter Surmon
[Crash log OBS MIDI.txt](https://github.com/cpyarger/obs-midi/files/5983043/Crash.log.OBS.MIDI.txt)

**Comment by cpyarger** [comment]
Working on it

**Comment by cpyarger** [comment]
Solved in latest release
