### ISSUE TITLE
This seems to happen WinMM::openPort: error creating Windows MM MIDI input port error happens whenever I start OBS

### ISSUE THREAD

**Issue by ericfont** [cpyarger/obs-midi#33]
When I open OBS I get:

![image](https://user-images.githubusercontent.com/6502474/108000614-63905100-6fb8-11eb-862d-0094ce1f1e5d.png)

which I can click through.  At this point OBS won't respond to the previously-saved midi device.  When I go to obs-midi settings, when I click on my previously-confiured device, I get that same error, which I have to click through 3 times.  "Bidirectional" is checked even though it wasn't saved, so I have to disable that checkbox.

But then everything seems to work.  The previous config for that midi device is still intact.

**Comment by cpyarger** [comment]
Normally means something is already using the midi device.

**Comment by cpyarger** [comment]
Also, There were issues previously on adding devices that are now fixed in the release put out today

**Comment by ericfont** [comment]
ah, the latest release seems to have fixed this MidiInWinMM::openPort issue.

I'm still noticing with the "Bidirectional" checkbox that even if I disable that checkbox prior to closing OBS, that upon reopening OBS that checkbox still gets enabled for my midi device.
