### ISSUE TITLE
Unable to set preview scene in action window

### ISSUE THREAD

**Issue by PSurmon** [cpyarger/obs-midi#42]
Good day

Many thanks for the swift response to my previous issue, much appreciated. My controller is now working. I am using OBS in studio mode and select scenes to preview before pushing them to program. In the actions drop down menu for "Set Current Scene" there is a further menu for selecting the scene, but for "Set Preview Scene" this seems to be missing.

Many thanks

Peter Surmon

**Comment by cpyarger** [comment]
This will be fixed shortly (: I already have it fixed just need to pull it in ^_^

**Comment by cpyarger** [comment]
Fixed
