### ISSUE TITLE
(mac) Enabled/Bi-directional settings not saving when closing OBS midi settings

### ISSUE THREAD

**Issue by esaiah** [cpyarger/obs-midi#45]
After turning off "enabled" or "bidirectional", closing the OBS MIDI settings, then re-opening the OBS MIDI settings, the "enabled" and "bidirectional" buttons will be back to default (checked)

![Screen Shot 2021-02-17 at 2 56 49 PM](https://user-images.githubusercontent.com/79030614/108278798-66ae4d00-7130-11eb-94f1-45f441559afb.png)

MAC os - 10.14.6
OBS - 26.1.2 (64bit)
OBS MIDI - obs-midi-e670278-macOS

Thx!

**Comment by cpyarger** [comment]
Closed, Fixes available shortly.
