### ISSUE TITLE
Crashes OBS when opening from tools menu

### ISSUE THREAD

**Issue by JSkye3293** [cpyarger/obs-midi#59]
[2021-02-19 23-00-34.txt](https://github.com/cpyarger/obs-midi/files/6014315/2021-02-19.23-00-34.txt)
[2021-02-19 22-57-59.txt](https://github.com/cpyarger/obs-midi/files/6014317/2021-02-19.22-57-59.txt)
[2021-02-19 22-56-41.txt](https://github.com/cpyarger/obs-midi/files/6014318/2021-02-19.22-56-41.txt)

OBS Will open just fine, but as soon as I try to open the tool OBS will crash. Here is my log file, I have tried it a few times with no luck. I was hoping to use this for an upcoming event on Sunday, dunno if its possible for a workaround?

[Crash 2021-02-19 22-57-39.txt](https://github.com/cpyarger/obs-midi/files/6014308/Crash.2021-02-19.22-57-39.txt)
[Crash 2021-02-19 22-58-48.txt](https://github.com/cpyarger/obs-midi/files/6014309/Crash.2021-02-19.22-58-48.txt)
[Crash 2021-02-19 23-01-11.txt](https://github.com/cpyarger/obs-midi/files/6014310/Crash.2021-02-19.23-01-11.txt)

**Comment by cpyarger** [comment]
I think I see the problem, Working on fix now

**Comment by cpyarger** [comment]
Will be pushing a new release to take care of this within the next hour

**Comment by JSkye3293** [comment]
Awesome thank you so much! I will let you know if this fixed my issue in the morning.
