### ISSUE TITLE
Crash while using obs-midi

### ISSUE THREAD

**Issue by Wilxx** [cpyarger/obs-midi#85]
## Platform
 MacBook Pro 15" (2012)
 (I know you don't get to test the MacOS but I'm reporting it to help you better understand the crashes).
Operating system and version: MacOS 10.15.7
OBS Studio version: 26.1.2

## Expected Behavior
 I get a crash randomly after a few minutes of using obs-midi. This can me at a random time and usually within a few minutes of mapping something or poking around the mapping interface. I'm not sure if it is connected to the memory leaks that you've described previously.

## Current Behavior
 OBS quits, gives me a crash report and restarts.
 The "Show crash report" option in OBS is not opening anything but the logs are.

## Steps to Reproduce

1. Open OBS and map some buttons in obs-midi.
2. There will be a time where the app will quit.
3. 
4.

## Additional information
 I am using a Pioneer DJ SP-1 MIDI controller with obs-midi.
[2021-02-28 15-58-15.txt](https://github.com/cpyarger/obs-midi/files/6057203/2021-02-28.15-58-15.txt)

**Comment by cpyarger** [comment]
What version of obs-midi are you running?

**Comment by Wilxx** [comment]
Hi

Sorry, I should have included that. I am running obs-midi-0c9ed43-macOS.pkg which was updated recently.

**Comment by Wilxx** [comment]
After checking, it seems obs-midi ALPHA 2 975d363 has a MacOS fix in it so I can give that a go and report back.

**Comment by Wilxx** [comment]
[OBS crash.txt](https://github.com/cpyarger/obs-midi/files/6057319/OBS.crash.txt)

**Comment by cpyarger** [comment]
is another application using the midi device? 
it looks like the error is ```
terminating with uncaught exception of type rtmidi::driver_error: MidiInCore::initialize: error creating OS-X MIDI client object (-50).``` 
I can look into it but I am not sure whats the actual problem is. I will check with the rtmidi17 people about this error and see what i find.

**Comment by Wilxx** [comment]
Fantastic. I was only using OBS at the time with nothing else. I will see if I can work anything out.

**Comment by cpyarger** [comment]
I have added a catch for the exception that is being thrown, and am building a new release it will be version 506315b and should be out in <10 minutes
you can view the progress of the release build here https://github.com/cpyarger/obs-midi/actions/runs/608294081

**Comment by cpyarger** [comment]
The new release is out https://github.com/cpyarger/obs-midi/releases/latest If you could test it out and let me know how it goes it would be appreciated

**Comment by Wilxx** [comment]
Hi

I tried the new version and it ran a lot longer before it crashed OBS. I will keep testing though as we seem to be getting somewhere. Hope these help.


[2021-02-28 18-43-34.txt](https://github.com/cpyarger/obs-midi/files/6057622/2021-02-28.18-43-34.txt)


[OBS crash 2.txt](https://github.com/cpyarger/obs-midi/files/6057614/OBS.crash.2.txt)

**Comment by cpyarger** [comment]
That looks like a crash in the browser source to me, I don't see any crashes on obs-midi's side.

**Comment by Wilxx** [comment]
Great news. No other crashes yet. I run a browser source with an overlay that pulls data from the Now Playing in my DJ application (Serato DJ). maybe it was that.

A very small issue with scroll bars/lists. Want me to open a fresh bug report for that?

**Comment by cpyarger** [comment]
Yes please
