### ISSUE TITLE
Horizontal scroll bar and list character amount quirk

### ISSUE THREAD

**Issue by Wilxx** [cpyarger/obs-midi#86]
## Platform

Operating system and version: MacOS 10.15.7
OBS Studio version: 26.1.2

## Expected Behavior
 A scroll bar issue and list labels. Being able to see all data.

## Current Behavior
 The bottom of the MIDI mapping box doesn't take into account the horizontal scroll bar so when you are at the bottom of the mapped list and there is no more scrolling available, the last row is obscured. Maybe add some space at the end of the mapped list to overcome this?

There is also a small dropdown list issue in the "Actions" area where the standard text "SCENE 2" has the number cropped off.
I can understand the label needs to end at some point but maybe have an extra few characters on the end so the preset labels are seen?

## Steps to Reproduce

1.
2.
3.
4.

## Additional information

![Screenshot 2021-02-28 at 18 36 30](https://user-images.githubusercontent.com/79801481/109430196-ffc64900-79f7-11eb-9bda-52f0d1ef325f.png)
![Screenshot 2021-02-28 at 19 13 17](https://user-images.githubusercontent.com/79801481/109430385-1325e400-79f9-11eb-98a6-c5582f5cec52.png)

**Comment by cpyarger** [comment]
Take a look at the latest release and let me know how it turns out for you?

**Comment by Wilxx** [comment]
@cpyarger Fantastic. The GUI has more info available. On the default scenes now. Many thanks
