### ISSUE TITLE
MIDI CHANNEL SETUP

### ISSUE THREAD

**Issue by sven1202** [cpyarger/obs-midi#91]
## Platform

Operating system and version: Mac OS 11.2.1
OBS Studio version: OBS 26.1.2

## Expected Behavior

When congifuring and mapping midi I should be able to change midi device channel, note and value.

## Current Behavior

The channel, note and value are all stuck at 0, and will not let me change them to anything within the standard 1-16 range.

**Comment by cpyarger** [comment]
Click Listen one, and toggle something on your board
or listen many and toggle something.

**Comment by cpyarger** [comment]
You can change message type, This is primarily so you can move between note on and note off if you are trying to quickly setup mappings that you want the button to activate on either
