### ISSUE TITLE
OBS Transition Duration

### ISSUE THREAD

**Issue by djtomt1200** [cpyarger/obs-midi#92]
I have the pads on my midi controller mapped to "Set Current transition" and those are working fine. I have another pad mapped to "Transition". Within OBS I have the Transition Duration set to 1000 ms. When I click the "Transition" button I have mapped, the Transition duration automatically defaults to 2 ms. Is there a way to change this value?

Operating system and version: Mac OS 10.14.6 Mojave
OBS Studio version: 26.1.2

## Expected Behavior
Transition uses default duration set by user in OBS

## Current Behavior
Transition Duration defaults to 2 ms

## Additional information
More info here: https://obsproject.com/forum/threads/obs-midi.125232/post-514965

**Comment by cpyarger** [comment]
Going to put out a new release that adds some limited support for this. 

if you are having issues changing the duration in obs-midi, try using your mouse wheel or clicking the arrow buttons

**Comment by cpyarger** [comment]
Looks like typing your value in works just fine on mac (: I am going to call this one closed.  if you have any other problems, just make a new issue (:

**Comment by djtomt1200** [comment]
Thanks so much for your quick response and update! Looking forward to future versions of this plugin. Very handy.
