### ISSUE TITLE
Crash when switching from regular OBS view to Studio Mode

### ISSUE THREAD

**Issue by djtomt1200** [cpyarger/obs-midi#94]
When I start OBS in Studio Mode, the app works like a champ.  Spot on scene and transition switching, no crashes that I have been able to detect.  I switched over to OBS regular mode to fine tune a particular scene.  When I switch back to Studio Mode and make a couple of MIDI button presses, the whole thing crashes.  Random buttons too.  I can't detect a pattern.  When I reopen OBS Studio in Studio Mode, everything works fine.

I have the controller's keyboard mapped to "Set Preview Scene" and the controller's pads
[Crash Report.pdf](https://github.com/cpyarger/obs-midi/files/6084497/Crash.Report.pdf)
 mapped to "Set Transition" with the last one in that group sent to "Transition". 

Operating system and version: Mac OS 10.14.6 Mojave
OBS Studio version: 26.1.2
MIDI Controller: Akai MPK Mini MKII

## Expected Behavior
Switch between OBS Studio Mode and regular mode without crashing

## Current Behavior
OBS Studio crashes when using MIDI controller upon switching from regular mode to studio mode

## Additional information
Apple crash report attached.

**Comment by cpyarger** [comment]
What plugin version?

**Comment by djtomt1200** [comment]
Oops. Sorry. This one: obs-midi ALPHA 2 5543a29

**Comment by cpyarger** [comment]
I am pushing out a new release, I can't really do any testing of this problem as I haven't been able to replicate it. but if you can let me know if the fixes change anything for you that would be great

**Comment by djtomt1200** [comment]
I tried installing obs-midi ALPHA 2 230057d and obs-midi ALPHA 2 52b5ca1.  When I installed those, the OBS MIDI Options selection in the OBS Tools Menu completely disappeared and I was no longer able to use my MIDI controller.

I installed obs-midi ALPHA 2 5543a29 and everything works again.  I haven't been able to reproduce the crash yet.  As soon (if) it happens I will let you know.

Please keep me posted what happened with the 2 most recent updates.  Thanks.

**Comment by djtomt1200** [comment]
Currently using  obs-midi ALPHA 2 5543a29 - had to downgrade to this version as the 2 newest ones didn't work at all.

I am on a MacBook Pro with 16 GB RAM running OS 10.14.6 Mojave and using an AKAI MPK Mini controller - same as before.

I have been able to recreate the issue several times now. This is how:

- start OBS in Studio Mode
- Preview scene switching and transitions work perfectly
- change to regular view in OBS
- change back to Studio Mode
- OBS will crash within 2-3 presses on the MIDI controller.  No pattern that I can detect.

Hope this helps.

Thanks.

**Comment by cpyarger** [comment]
Got the newest release working on mac, was a library linking issue with the new libraries. 

Let me know if you are still crashing please

**Comment by djtomt1200** [comment]
Now using: obs-midi ALPHA 2 b700f43

OBS still crashes after switching to regular mode and then back to studio mode. However it takes many more keystrokes/button presses on my MIDI controller to make the crash happen now.  I can't detect a pattern to it yet.

**Comment by cpyarger** [comment]
Upload the crash reports and log files (: the option is under the help menu 

Just drop the link

**Comment by djtomt1200** [comment]
Crash reports here: https://www.dropbox.com/sh/gp43hjshrdzqmxp/AAAlSWegV7W7ARgFLbhhPUAya?dl=0

**Comment by djtomt1200** [comment]
Just added another crash report to the same folder linked above.  Thanks.

**Comment by cpyarger** [comment]
the last Two of those are from the browser source causing a crash lol

**Comment by djtomt1200** [comment]
Whoops. My bad. Lol. Bear with me. I am new at this. Thanks.

**Comment by cpyarger** [comment]
No problem (:

**Comment by djtomt1200** [comment]
Updated to obs-midi 0.9.3-ALPHA-3.11 - crash issues seem to be resolved. Will report back if not. Thank you again for your quick response and updates. Greatly appreciated. This is a fantastic plugin!

**Comment by cpyarger** [comment]
No problem
