### ISSUE TITLE
mac: obs-midi plugin is not loaded (QtWidgets not found)

### ISSUE THREAD

**Issue by renchap** [cpyarger/obs-midi#98]
## Platform

Operating system and version: macOS 11.2.2
OBS Studio version: 26.1.2

## Expected Behavior

I expect obs-midi to appear in the Tools menu

## Current Behavior
Nothing appears in the menu

Relevant lines in logs:

```
22:47:11.636: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so->/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so, 257): Library not loaded: /tmp/obsdeps/lib/QtWidgets.framework/Versions/5/QtWidgets
22:47:11.636:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so
22:47:11.636:   Reason: image not found
22:47:11.636: 
22:47:11.636: Module '/Library/Application Support/obs-studio/plugins/obs-midi/bin/obs-midi.so' not loaded
```

## Steps to Reproduce
I just installed Jack, first from Hemebrex then via the website, tried to relaunch OBS, and then checked the logs. I was expecting an issue with Jack, but its not the case it seems.

## Additional information
Not sure on how to repro, but I can dig further if you want more details

**Comment by cpyarger** [comment]
Taking a look now, I made some changes to speed up the CI pipeline, and it may have broken things.

**Comment by cpyarger** [comment]
I think I see the issue now, QT used to be included on a different path, updating path now and giving it a test. Ill keep you updated

**Comment by cpyarger** [comment]
Got it fixed (: new release is out

**Comment by renchap** [comment]
Thanks, it fixed the issue !
